#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define NO_ERRORS 0
#define SERIAL_WRITE_FAIL 1
#define SERIAL_WRITE_SUCCESS 2
#define SERIAL_READ_FAIL 3
#define SERIAL_READ_SUCCESS 4
#define PING_SUCCESS 5
#define PING_FAIL 6
#define SERIAL_TIMEOUT_ERROR 7



#endif
